server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts: ["10.33.61.120"]
  cluster: prod-transactfoxtrot-elasticsearch
  tableNamePrefix: foxtrot
  countQueryTimeout: 10000
  fetchQueryTimeout: 10000


hbase:
  secure : false
  tableName: foxtrot
  coreSite: /etc/hadoop/conf/core-site.xml
  hdfsSite: /etc/hadoop/conf/hdfs-site.xml
  hbasePolicy: /etc/hbase/conf/hbase-policy.xml
  hbaseSite: /etc/hbase/conf/hbase-site.xml
  seggregatedTablePrefix: foxtrot-
  rawKeyVersion: 2.0

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60